### ISSUE TITLE
A question and a suggestion.

### ISSUE THREAD

**Issue by simurgh9** [UvA-FNWI/M365-IMAP#1]
##### Question

Does the refresh token not change? If it does, would it need to be updated manually each time in `offlineimap`? 

##### Suggestion

You should make the documentation link of `offlineimap`'s ability to handle XOAUTH2 be this,

https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L897

**Comment by goomens** [comment]
The refresh token typically doesn't change, unless a change is made to the account (e.g. a password or MFA reset), in which case it needs to be done again (but in a typical production setup this will be rare).

I've added the link to the config/documentation, thanks for the suggestion!
