### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by benmont** [UvA-FNWI/M365-IMAP#10]
This project doesn't include a license. Adding a license or relicensing requires consent of all contributors, so it'd be good to add one before accepting more contributions. I recommend the [MIT license](https://choosealicense.com/licenses/mit/).

**Comment by goomens** [comment]
Good point. If @cakemanny and @arjunkc have no objections, I'll add the MIT license

**Comment by cakemanny** [comment]
No objection from me 👍

**Comment by arjunkc** [comment]
None from me either

**Comment by benmont** [comment]
Thanks!
