### ISSUE TITLE
Stopped working and I get Bad request from offlineimap

### ISSUE THREAD

**Issue by noorul** [UvA-FNWI/M365-IMAP#12]
offlineimap returns

ERROR: Exceptions occurred during the run!
ERROR: HTTP Error 400: Bad Request (configuration is: {'client_id': '08162f7c-0fd2-4200-a84a-f25a4db0b584a', 'client_secret': 'TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82', 'refresh_token': 'xxxxxxxx', 'grant_type': 'refresh_token'})

Everything was working fine until now

**Comment by cgraefe** [comment]
I just encountered a similar issue. Creating a new refresh token fixed it for me.

**Comment by noorul** [comment]
This is fixed after I started using org id as part of `Authority` URL in config.py
