### ISSUE TITLE
Filter out Calendar and Contacts

### ISSUE THREAD

**Issue by arjunguha** [UvA-FNWI/M365-IMAP#4]
Thanks for putting this together! Works like a charm. At my institution, I had to add this `folderfilter` to suppress lots of spurious errors:

```
[Repository Remote]
...
folderfilter = lambda folder: not folder.startswith('Calendar') and not folder.startswith('Contacts')
```

I figured this may help someone.

**Comment by goomens** [comment]
Thanks, I've added a comment about this!
